services:

  mysql:
    image: mysql:8.0
    container_name: payment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: paymentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  payment-service:
    build: .
    container_name: payment-service
    depends_on:
      - mysql
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paymentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql_data: