# Never use hardcoded values ? use env vars injected by ECS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Security headers
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

# Disable actuator endpoints in prod except health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never