spring.application.name=paymentService

spring.datasource.url=jdbc:mysql://mysql:3306/paymentdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=8080

# Actuator

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# eureka
eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}



eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${PAYMENT_ALB_HOST}
eureka.instance.non-secure-port=80
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}

# Consumer Configuration
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

